name: the_meet_app

description: "A flutter app for organizing meetups"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_app_check: ^0.2.2
  # Google Sign In
  google_sign_in: ^6.2.1
  # State management
  provider: ^6.1.1  # Maps & Location
  flutter_map: ^6.1.0
  google_maps_flutter: ^2.5.3
  google_places_flutter: ^2.0.6
  latlong2: ^0.9.0
  # Utility packages
  flutter_polyline_points: ^2.0.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  get_it: ^8.0.3
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.7  # Performance optimization packages
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.1
  device_info_plus: ^10.1.0  # Replace fluttertoast with more compatible toast solution
  toastification: ^2.3.0
  # Notifications for panic alerts
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/meet_images/

